config/routes.rb
Rails.application.routes.draw do
  root 'page#home'
  get 'about', to: 'page#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum:50}
    validates :description, presence: true, length: {minimum: 13, maximum:300}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false}, 
            length: { minimum: 3, maximum: 30}

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            uniqueness: { case_sensitive: false}, 
            length: { maximum: 130},
            format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update,:destroy,:show]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  def new
      @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "the article successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "the article successfully updated"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    
  end

  def show
    
  end

  def destroy
    @article.destroy
    flash[:danger] = "the article successfully deleted"
    redirect_to articles_path
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have Successfully Logged in "
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out "
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:success] = "your account successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user been deleted"
    redirect_to users_path
  end
  private
  def set_user
    @user =User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def require_same_user
    if current_user != @user and  !current_user&.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in?  and ! current_user.admin?
      flash[:danger] = "Only Admin user can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle z-depth-2")
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row spacing">
    <div class=" col-10 offset-1">
      <div class="card card-lg bg-light">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length:100) %> </br>
         </br>
            <small class="article-meta-details">Created by: <%= article.user.username if article.user %></br>
                    <%= time_ago_in_words(article.created_at)%> ago</br>
                    last updated: <%= time_ago_in_words(article.updated_at)%> ago</small>
          
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions spacing-btn">
            <%= link_to "Edit this article", edit_article_path(article), class:"btn btn-primary " %>
            <%= link_to "Delete this article", article_path(article), method: :delete, data: {confirm: "Are you sure?" }, class:"btn btn-danger "%>
          </div>
        <% end %>
      </div>  
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class='row g-3 align-items-center'>
  <div class="mb-3">
    <%= form_for @article do |f| %>
      <div class="form-group">
        <div class="col-sm-2 col-form-label ">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "title of article", autofocus: true %>
        </div></br>
      </div>
      <div class="form-group">
        <div class="col-sm-2 col-form-label ">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "body of article"%>
        </div>
      </div>
      <div class="form-group">
        <div class="offset-3 col-sm-10"></br>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-4 offset-2"></br>
      [ <%= link_to "Cancel request and return to article list ", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div class="center-2">
  <%= will_paginate %>
</div>
<%= render "article", obj: @articles %>
<div class="center-2">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1> create article</h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align="center">title: <%= @article.title %></h2>
<div class="card card-body bg-light col-10 offset-1">
<% if @article.user %>
  <ul class="listing">
    <div class='row align'>
      <div class="col-md-3 offset-md-3" id="gravatar">
        <li>created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <li class="article-title">
          <%= link_to @article.user.username,  user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </div>  
  </ul>
<% end %>
  <h4 class="col-md-3 offset-md-4 description"><strong>  Description:</strong></h4>
  <hr>
 
  <%= simple_format(@article.description) %> </br>
  <div class="article-body">
 
      <small>Created by: <%= @article.user.username if @article.user %>,</br>
              <%= time_ago_in_words(@article.created_at)%> ago,</br>
              last updated: <%= time_ago_in_words(@article.updated_at)%> ago</small>
    
  </div>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?)  %>
      <%= link_to "Edit this article", edit_article_path(@article), class:"btn btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure?" }, class:"btn btn-danger"%>
    <% end %>
    <%= link_to "View all article list ", articles_path, class:"btn btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
      <small>
        Copyright &copy; Pradeep kumar
      </small>
      <nav>
        <ul>
          <li><%#= link_to "About", about_path %></li>
        </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
  <div class="row">
    <div class="col-8 offset-2">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %> alert-dismissible fade show' role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
   
    <%= link_to 'Blog', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path,class:"nav-link" %>
          
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link" %>
        </li>
        <% if logged_in?%>
          <li><%= link_to "New Article", new_article_path, class:"nav-link" %></li>
          
        <% end %>
     
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    
     
        <ul class="navbar-nav  navbar-right">
          <% if logged_in? %>
            <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class:"nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Your Profile <%= "Admin" if current_user.admin? %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Edit you profile", edit_user_path(current_user), class:"dropdown-item" %></li>
                <li><%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %></li>
               
              </ul>
            </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path , class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "sign up", signup_path , class:"nav-link"%>
          </li>
          <% end %>
        </ul>
     
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Blog</title>
  </head>
  <body>
    <%= render 'layouts/nav'%> </br>
    <%= render 'layouts/messages'%> 
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/page/about.html.erb
<h1>About Blog application</h1>
<p>In this Application User can create an artical, edit an article, and delete an article</p>
<p>User without login can view all article and users and create their own account to create an article</p>

app/views/page/home.html.erb
 <div class="header">
  <div class="main-container">
      <div class="row_home">
          <div class="col-2">
            <h1>My Blog</h1>
            <h1> to create account</h1>
            <%= link_to "sign up", signup_path, class:"btn btn-primary btn-lg" %>
          </div>
          <div class="col-2" >
              <img src="images/rails.png" id="space">
          </div>
      </div>
  </div>
</div> 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class="col-10 offset-1 ">
      <div class="alert alert-danger">
        <div class="alert-heading">
          <h2 class="alert-title">
            <%= pluralize(obj.errors.count, "error")%>
            probiheted this article from being saved:
          </h2>
          <div class="alert-body">
            <ul>
              <% obj.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class='row g-3 align-items-center'>
  <div class="mb-3">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <div class="col-sm-2 col-form-label ">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div></br>
      </div>
      <div class="form-group">
        <div class="col-sm-2 col-form-label ">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter Email"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 col-form-label ">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter Password"%>
        </div>
      </div>
      <div class="form-group">
        <div class="offset-3 col-sm-10"></br>
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update account",class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
    <div class="col-4 offset-2"></br>
      [ <%= link_to "Cancel request and return to article list ", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit Your Account</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 align="center">All Bloggers</h1>
<div align="center">
  <div class="center-2">
    <%= will_paginate %>
  </div>

  <% @users.each do |user|%>
    <ul class="listing">
      <div class='row'>
        <div class="card card-body md-4 offset-1">
          
          <li><%= link_to gravatar_for(user), user_path(user) %>
          <li class="article-title">
            <%= link_to user.username,  user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Delete this user", user_path(user), method: :delete, data:{ confirm: "Are you sure you want to delete the user and all their articles?"}, class: 'btn btn-danger btn-lg' %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <%end%>
  <div class="center-2">
    <%= will_paginate %>
  </div>

</div>

app/views/users/new.html.erb
<h1 >Signup for Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class='row'>
  <div class="md-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s article</h4>
<div class="center-2">
  <%= will_paginate @user_articles %>
</div>
<%= render "articles/article", obj: @user_articles %>
<div class="center-2">
  <%= will_paginate @user_articles %>
</div>